sudo: required
services:
  - docker

before_install:
  - echo "building dev image"
  - docker build -t personal-finance-app-client -f Dockerfile.dev .

script:
  - docker run -e CI=true personal-finance-app-client npm run test

after_success:
  - chmod +x dockerhub.sh
  - ./dockerhub.sh

deploy:
  edge: true
  provider: elasticbeanstalk
  region: 'eu-west-2'
  app: 'personal-finance-app-client'
  env: 'PersonalFinanceAppClient-test-env'
  bucket_name: 'elasticbeanstalk-eu-west-2-406965596077'
  bucket_path: 'personal-finance-app-client'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
