sudo: required
services:
  - docker

before_install:
  - docker build -t personal-finance-app-client -f Dockerfile.dev .

script:
  - docker run -e CI=true personal-finance-app-client npm run test

after_success:
  - docker build --build-arg "$COGNITO_USER_POOL_ID "--build-arg "$COGNITO_CLIENT_ID" -t ian035/personal-finance-app-client .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ian035/personal-finance-app-client

deploy:
  edge: true
  provider: elasticbeanstalk
  region: 'eu-west-2'
  app: 'personal-finance-app-client'
  env: 'PersonalFinanceAppClient-test-env'
  bucket_name: 'elasticbeanstalk-eu-west-2-406965596077'
  bucket_path: 'personal-finance-app-client'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
